import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingBottom: 8,
    backgroundColor: '#0a0a0a',
    borderBottomWidth: 1,
    borderBottomColor: '#252525',
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    gap: 6,
  },
  tabActive: {
    backgroundColor: '#151515',
  },
  tabText: {
    fontSize: 13,
    color: '#6b5d50',
    fontWeight: '400',
  },
  tabTextActive: {
    color: '#a67c52',
    fontWeight: '500',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 30,
  },
  header: {
    paddingTop: 32,
    paddingBottom: 32,
    paddingHorizontal: 24,
    backgroundColor: '#0a0a0a',
  },
  headerContent: {
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '300',
    color: '#c9b8a8',
    marginTop: 12,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#8a7d70',
    textAlign: 'center',
    fontWeight: '300',
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#151515',
    borderWidth: 2,
    borderColor: '#a67c52',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#252525',
  },
  statNumber: {
    fontSize: 28,
    fontWeight: '300',
    color: '#c9b8a8',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: '#8a7d70',
    textAlign: 'center',
    fontWeight: '300',
  },
  artworksContainer: {
    paddingHorizontal: 24,
    marginTop: 32,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#c9b8a8',
    marginBottom: 16,
    letterSpacing: 1,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#8a7d70',
    marginTop: 20,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 13,
    color: '#6b5d50',
    textAlign: 'center',
    paddingHorizontal: 32,
    lineHeight: 22,
    fontWeight: '300',
  },
  artworksList: {
    gap: 16,
  },
  artworkCard: {
    flexDirection: 'row',
    backgroundColor: '#151515',
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#252525',
  },
  artworkImage: {
    width: 100,
    height: 120,
  },
  artworkInfo: {
    flex: 1,
    padding: 16,
    justifyContent: 'space-between',
  },
  artworkHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  artworkTitleContainer: {
    flex: 1,
  },
  artworkTitle: {
    fontSize: 15,
    fontWeight: '400',
    color: '#c9b8a8',
    marginBottom: 4,
  },
  artworkArtist: {
    fontSize: 12,
    color: '#8a7d70',
    fontWeight: '300',
  },
  favoriteButton: {
    padding: 4,
  },
  artworkFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateText: {
    fontSize: 11,
    color: '#6b5d50',
    fontWeight: '300',
  },
  shareSection: {
    paddingHorizontal: 24,
    marginTop: 32,
  },
  shareCard: {
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 24,
    borderWidth: 1,
    borderColor: '#252525',
  },
  shareTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#c9b8a8',
    marginBottom: 8,
  },
  shareText: {
    fontSize: 13,
    color: '#8a7d70',
    lineHeight: 22,
    marginBottom: 20,
    fontWeight: '300',
  },
  shareButton: {
    borderRadius: 4,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#a67c52',
    paddingVertical: 14,
    alignItems: 'center',
  },
  shareButtonText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#c9b8a8',
  },
  actionsContainer: {
    paddingHorizontal: 24,
    marginTop: 24,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#252525',
    gap: 12,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#c9b8a8',
  },
  profileSection: {
    paddingHorizontal: 24,
    marginTop: 24,
  },
  profileStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  profileStatCard: {
    width: '48%',
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#252525',
  },
  profileStatNumber: {
    fontSize: 24,
    fontWeight: '300',
    color: '#c9b8a8',
    marginTop: 12,
    marginBottom: 4,
  },
  profileStatLabel: {
    fontSize: 11,
    color: '#8a7d70',
    textAlign: 'center',
    fontWeight: '300',
  },
  badgesContainer: {
    gap: 12,
  },
  badgeCard: {
    // flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#a67c52',
    gap: 16,
  },
  badgeCardLocked: {
    borderColor: '#252525',
    opacity: 0.5,
  },
  badgeIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(166, 124, 82, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeIconLocked: {
    backgroundColor: '#151515',
  },
  badgeTitle: {
    fontSize: 15,
    fontWeight: '400',
    color: '#c9b8a8',
    flex: 1,
  },
  badgeDescription: {
    fontSize: 12,
    color: '#8a7d70',
    fontWeight: '300',
  },
  profileMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#252525',
    gap: 12,
    marginBottom: 12,
  },
  profileMenuText: {
    fontSize: 15,
    fontWeight: '400',
    color: '#c9b8a8',
  },
  settingsSection: {
    paddingHorizontal: 24,
    marginTop: 24,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#252525',
    marginBottom: 12,
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  settingTextContainer: {
    flex: 1,
  },
  settingTitle: {
    fontSize: 15,
    fontWeight: '400',
    color: '#c9b8a8',
    marginBottom: 2,
  },
  settingDescription: {
    fontSize: 12,
    color: '#8a7d70',
    fontWeight: '300',
  },
  settingMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#151515',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#252525',
    gap: 12,
    marginBottom: 12,
  },
  settingMenuText: {
    fontSize: 15,
    fontWeight: '400',
    color: '#c9b8a8',
  },
});
